name: Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r deployed_app/flask/requirements.txt

      - name: Run basic tests
        run: |
          cd deployed_app/flask
          python -m pytest ../../deployed_app/tests

      - name: Build Docker container
        run: |
          cd deployed_app
          docker build -f docker/Dockerfile -t canteen-flask-app .
